### ISSUE TITLE
Does threadcap sanitize the content of comments?

### ISSUE THREAD

**Issue by dellagustin** [skymethod/minipub#5]
Hello @johnspurlock-skymethod ,

This is coming from https://github.com/Podcastindex-org/web-ui/pull/218#issuecomment-1407558312.
Does thread cap sanitize the html on the comments content?

Best Regards.

**Comment by johnspurlock** [comment]
Sanitize? That's kind of not at threadcap's abstraction layer - its job is to collect the underlying content from the various sources, hiding the ap/mastodon calls.

Each app might want to do different things to the raw contents to show it off, it's not one-size-fits-all, so that's best left to the renderer, ie you in this case : )

**Comment by johnspurlock-skymethod** [comment]
Sanitize? That's kind of not at threadcap's abstraction layer - its job is to collect the underlying content from the various sources, hiding the ap/mastodon calls.

Each app might want to do different things to the raw contents to show it off, it's not one-size-fits-all, so that's best left to the renderer, ie you in this case : )

**Comment by dellagustin** [comment]
Agreed, just wanted to be sure, thanks!
